export const ROUTE_CONSTANTS = {
  LOGIN: '/login',
  FORGET_PASSWORD: '/forgetpassword', // to send otp on email
  RESET_PASSWORD: '/resetpassword',
  RESET: '/v/reset',
  DASHBOARD: '/dashboard',
  MASTER: '/master',
  CONTRACT: '/contract',
  INVOICE: '/invoice',
  PAYMENT: '/payment',
  PER_INVOICE: '/per_invoice',
  INVENTORY: '/inventory',
  COUPON_HISTORY: '/coupon/history',
  TOTAL_TRANSACTION: '/totaltransaction',
  SETTINGS: '/settings',
  LAYOUT: '/',
  SOCIAL_AUTH: '/SocialAuth',
  AGGREGATOR_ANALYTICS: '/aggregator',
  VEGAPRO: '/vegapro',
  RECHARGE: '/recharge',
  AGGREGATOR_REPORTS: '/aggregator/reports',
  AGGREGATOR_SETTINGS: '/aggregator/settings',
  AGGREGATOR_SUPPORT: '/aggregator/support',
  AGGREGATOR_PLATFORM_PREFERENCE: '/aggregator/platform-preference',
  AGGREGATOR_MANAGE_USER: '/aggregator/manage-user',
  SUPERADMIN_DASHBOARD: '/superadmin/dashboard',
  SUPERADMIN_USERS: '/superadmin/users',
  SUPERADMIN_CLIENTS: '/superadmin/clients',
  SUPERADMIN_INVENTORY: '/superadmin/inventory',
  SUPERADMIN_COUPON_HISTORY: '/superadmin/coupon/history',
  SUPERADMIN_TRANSACTION: '/superadmin/transaction',
  SUPERADMIN_SETTINGS: '/superadmin/settings',
  SUPERADMIN_MANAGE_USER: '/superadmin/manage-user',
  // PAYMENT: '/payments',
  ALL_COUPONS: '/all-coupons',
  AGGREGATOR_DASHBOARD: '/aggregator/dashboard',
  AGGREGATOR_CLENT_INFO: '/aggregator/client-info',
  AGGREGATOR_WALLET_INFO: '/aggregator/wallet-info',
  AGGREGATOR_WALLETWISE_INFO: '/aggregator/wallet-wise-info',
  GENERATE_INVOICE: '/generateinvoice',
  MANAGE_STORE: '/managestore',
}
